version: '3.7'

services:
  restaurant-app-web:
    image: restaurant-app-web
    container_name: restaurant-products-web-container
    depends_on:
      - restaurant-products-app
    hostname: localhost
    ports:
      - 9080:8080

  restaurant-products-app:
    build: .
    container_name: restaurant-products-app-container
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysqldbserver
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldbserver:3306/javauser?serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: javauser
      SPRING_DATASOURCE_PASSWORD: javauser
    networks:
      - backend

  mysqldbserver:
    image: mysql:8
    container_name: restaurant-products-db-container
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: javauser
      MYSQL_USER: javauser
      MYSQL_PASSWORD: javauser
      MYSQL_ROOT_PASSWORD: javauser
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend: